package chat;


/**
* chat/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Tuesday, June 16, 2015 4:36:01 PM CEST
*/

public interface ChatClientOperations 
{
  void update (String nick, String text);
} // interface ChatClientOperations
