package chat;


/**
* chat/ChatServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Tuesday, June 16, 2015 4:36:01 PM CEST
*/

public interface ChatServerOperations 
{
  String subscribe (String nick, chat.ChatClient c) throws chat.NameAlreadyUsed;
  void unsubscribe (String id) throws chat.UnknownID;
  void comment (String id, String text) throws chat.UnknownID;
} // interface ChatServerOperations
