package chat;


/**
* chat/UnknownID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* Tuesday, June 16, 2015 4:36:01 PM CEST
*/

public final class UnknownID extends org.omg.CORBA.UserException
{

  public UnknownID ()
  {
    super(UnknownIDHelper.id());
  } // ctor


  public UnknownID (String $reason)
  {
    super(UnknownIDHelper.id() + "  " + $reason);
  } // ctor

} // class UnknownID
